# Generated by Django 5.2 on 2025-04-10 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webscraper', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Item1',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('date_time', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Item2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('date_time', models.CharField(max_length=255)),
            ],
        ),
        migrations.DeleteModel(
            name='TodoItem',
        ),
    ]
